# Site settings
title: Simon Wolf's Writings
email: simon@swwritings.com
description: > # this means to ignore newlines until "baseurl:"
  My blog covers a range of topics ranging from work-related Cocoa development to indoor rowing, from photography to general technology and small business management.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://swwritings.com" # the base hostname & protocol for your site
twitter_username: sgaw
github_username:  ottersoftware

# Build settings
markdown: kramdown
